Shallow clone all submodules
ucb-bar/chipyard pull request #1064
Opened 2021-12-17 01:01 UTC by jerryz123

This might improve clone times.

**Type of change**: new feature

**Impact**: software change

**Release Notes**

Switch to shallow clone of all submodules

2021-12-20 22:26 UTC, abejgonzalez approved these changes
LGTM!

2021-12-20 22:40 UTC, jerryz123 commented
Don't merge this yet. The commit on master tests are broken.

2022-02-02 17:38 UTC, abejgonzalez requested changes
Can we get this fixed before the next release?

2022-02-14 18:48 UTC, abejgonzalez commented
Looks like CI is erroring because of https://github.com/actions/checkout/pull/424.

2022-02-16 05:27 UTC, merged