Update CHANGELOG.md
ucb-bar/chipyard pull request #1156
Opened 2022-04-07 23:48 UTC by sagark

I really just want to re-run CI with #1153 already merged.

2022-04-08 00:20 UTC, abejgonzalez commented
@Mergifyio rebase

2022-04-11 17:33 UTC, abejgonzalez commented
This is the submodule issue that is hurting us: https://github.com/actions/checkout/issues/358.

2022-04-11 19:16 UTC, abejgonzalez approved these changes
LGTM. Pending CI.

2022-04-11 19:16 UTC, abejgonzalez commented
@jerryz123 Can you review this? @sagark Can you review this (with a comment since the GH UI won't allow you to be a review since you opened the PR).

2022-04-11 19:22 UTC, jerryz123 requested changes
Can the repeated `Delete old checkout` steps not be coalesced into a single script? 
Also, for safety it might be good to have the script reference the directory defined in `defaults.sh`. `rm -rf ./*` is scary.

2022-04-11 20:54 UTC, jerryz123 approved these changes

2022-04-12 16:42 UTC, merged