Filter CI on PR contents + Mergify support
ucb-bar/chipyard pull request #1157
Opened 2022-04-08 01:20 UTC by abejgonzalez

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as "Please Backport"?

**Release Notes**
This PR is copying FireSim's automation for CI which does the following:
- Selectively run certain parts of the CI pipeline based on the files added
- If a backport request is asked, have mergify automate the backport PR (if a label called "Please Backport" is added)
- Use labels to determine what to put in a future changelog (not implemented yet, but figured it would be good to copy this)

Additionally, this PR changes a bit of the wording of the issue/PR templates (in addition to adding new fields specifying what users should do for automation).

2022-04-08 01:28 UTC, abejgonzalez commented
I'll post an issue for someone to optimize the filters a bit more later (have specific file paths trigger specific CI paths).

2022-04-13 04:30 UTC, abejgonzalez commented
@Mergifyio rebase

2022-04-13 04:35 UTC, jerryz123 approved these changes

2022-04-13 04:35 UTC, jerryz123 commented on .github/workflows/chipyard-run-tests.yml
> +            docs: &docs-filter
I think this decreases coverage. As this won't catch changes to the read the docs links in the code

2022-04-13 04:35 UTC, jerryz123 requested changes
I don't think we can limit when docs are built. Anyways doc building is fast. No need to skip

2022-04-13 20:22 UTC, sagark commented on .mergify.yml
> +          - 1.13.x
```suggestion
          - 1.13.x
```
```suggestion
          - 1.6.x
```

2022-04-13 20:22 UTC, sagark commented on .mergify.yml
> +          - 1.13.x
```suggestion
          - 1.13.x
```
```suggestion
          - 1.6.x
```

2022-04-15 16:39 UTC, jerryz123 approved these changes

2022-04-15 23:12 UTC, merged