DROMAJO_ROM variable fix
ucb-bar/chipyard pull request #1197
Opened 2022-07-13 17:24 UTC by jzhou1318

`DROMAJO_ROM `needs to point at `bootrom.rv64.img` which exists at `$(base_dir)/generators/testchipip/src/main/resources/testchipip/bootrom/bootrom.rv64.img` instead of `$(base_dir)/bootrom/bootrom.rv64.img`

**Type of change**:
- [x] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [x] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [x] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [x] (If applicable) Did you add documentation for the feature?
- [x] (If applicable) Did you add a test demonstrating the PR?

- [x] (If applicable) Did you mark the PR as `Please Backport`?

2022-07-13 17:28 UTC, jerryz123 approved these changes
Thanks!

2022-07-18 14:45 UTC, abejgonzalez requested changes

2022-07-18 14:45 UTC, abejgonzalez commented on tools/dromajo/dromajo.mk
> +DROMAJO_ROM = $(base_dir)/generators/testchipip/src/main/resources/testchipip/bootrom/bootrom.rv64.img
This should point to the bootrom that was copied into the build directory. If you look at this: https://github.com/ucb-bar/chipyard/blob/992664220d95edf610475031fd8a82d0cd743f7f/common.mk#L98, I copy the bootrom from testchipip to the build directory.

2022-07-20 18:39 UTC, jerryz123 approved these changes

2022-07-20 22:53 UTC, abejgonzalez approved these changes
LGTM

2022-07-20 23:04 UTC, merged