Add initial pre-commit support
ucb-bar/chipyard pull request #1294
Opened 2022-12-21 21:13 UTC by abejgonzalez

See https://github.com/firesim/firesim/pull/1329 for more original PR.

This adds

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [ ] Other enhancement

**Impact**:
- [ ] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

2022-12-21 21:48 UTC, jerryz123 commented
Neat. What happens when you break one of the rules? Does it fix your commit for you?

2022-12-21 22:12 UTC, tymcauley commented
It looks like it edited some `.svg` files. Is that bad? Seems like it shouldn't search for whitespace issues in a binary file.

2022-12-21 22:19 UTC, jerryz123 commented
SVGs are XML files, interestingly.

2022-12-21 22:21 UTC, tymcauley commented
> SVGs are XML files, interestingly.

🤯

2022-12-21 22:50 UTC, abejgonzalez commented
If there is a breakage it can either warn you and exit or edit the files itself.

2022-12-21 22:52 UTC, abejgonzalez commented
I also just enabled all the pre-commit hooks since I think there isn't much movement in the repo right now. So now could be a good time to just force formatting on everything.

2022-12-21 23:07 UTC, abejgonzalez commented
For reference on the Clang formatting: https://zed0.co.uk/clang-format-configurator/

2022-12-21 23:43 UTC, abejgonzalez commented
Note that the documentation error is not due to this PR (the BOOM documentation / website is down for some reason)

2022-12-21 23:44 UTC, jerryz123 commented on vlsi/example-vlsi
> -
I don't think these changes are an improvement.

2022-12-21 23:45 UTC, jerryz123 commented on vlsi/view_gds.py
> -            (50, 0),    #M5
Another example, this destroyed the formatting

2022-12-21 23:45 UTC, jerryz123 commented on fpga/src/main/resources/vcu118/sdboot/include/devices/gpio.h
> +#define GPIO_PULLUP_EN (0x10)
Not an improvement

2022-12-21 23:47 UTC, jerryz123 requested changes
I don't like forcing formatting on source code like this. No-trailing-whitespace is fine, but restructuring code and comments like this is too heavy-handed.

2022-12-22 00:01 UTC, abejgonzalez commented
I personally think having a linter/code-formatter is better than not having one at all, but we can push that to a later discussion. For now this PR will just focus on whitespace management + checking files.

2022-12-22 02:46 UTC, abejgonzalez commented
@jerryz123 This is now ready for rereview

2022-12-22 02:51 UTC, jerryz123 approved these changes
Thanks for fixing all the trailing-whitespace/newline issues. The git hooks thing seems useful.

2022-12-22 04:12 UTC, merged