REFACTOR: change bootaddr register address and PC reset vector address
ucb-bar/chipyard pull request #1605
Opened 2023-09-24 02:23 UTC by T-K-233

Go along with PR in testchipip [#196](https://github.com/ucb-bar/testchipip/pull/196)

The motivation is that the current organization of the bootrom code and the reset vector is rather confusing. One would normally assume that the reset vector is pointed toward the base of a memory section (e.g. 0x10000).

This could also benefit future bootrom code development.

The boot-up sequence of the SoC would now be:

PC resets at address `0x00010000`, and reads from the BootROM code. Within the BootROM code, the hart will read from BOOTSEL register, which is controlled by a external boot select pin, located at `0x00001000` on the memory map, to determine the following boot sequence. 

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [x] RTL change
- [x] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [x] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [x] Did you state the type-of-change/impact?
- [x] Did you delete any extraneous prints/debugging code?
- [x] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

2023-10-31 21:49 UTC, jerryz123 requested changes
I found the bug, check my comment in your testchipip PR.

Can you also update the docs references to `0x10040`? After that this should be fine

2023-11-02 19:28 UTC, jerryz123 commented
Thanks for seeing this through @T-K-233 .
@abejgonzalez any opposition? I think we've checked all the boxes for this major change.

If there is no opposition, I can fix the remaining merge conflict, and merge this.

2023-11-02 22:10 UTC, abejgonzalez commented
SFTM. I do like the change to always start at 0x10000 and go up from there.

2023-11-02 22:21 UTC, jerryz123 approved these changes

2023-11-02 22:34 UTC, merged