Use SV48 when possible
ucb-bar/chipyard pull request #1847
Opened 2024-04-12 22:39 UTC by abejgonzalez

Default to using SV48 for 64b designs. Otherwise, adhere to the RC default (SV32).

**Related PRs / Issues**:

**Type of change**:
- [ ] Bug fix
- [ ] New feature
- [x] Other enhancement

**Impact**:
- [x] RTL change
- [ ] Software change (RISC-V software)
- [ ] Build system change
- [ ] Other

**Contributor Checklist**:
- [ ] Did you set `main` as the base branch?
- [ ] Is this PR's title suitable for inclusion in the changelog and have you added a `changelog:<topic>` label?
- [ ] Did you state the type-of-change/impact?
- [ ] Did you delete any extraneous prints/debugging code?
- [ ] Did you mark the PR with a `changelog:` label?
- [ ] (If applicable) Did you update the conda `.conda-lock.yml` file if you updated the conda requirements file?
- [ ] (If applicable) Did you add documentation for the feature?
- [ ] (If applicable) Did you add a test demonstrating the PR?

- [ ] (If applicable) Did you mark the PR as `Please Backport`?

2024-04-12 22:39 UTC, abejgonzalez commented
This was tested in a CY/FS setup on both BOOM and Rocket default designs (booting Linux - buildroot + Ubuntu).

2024-04-12 22:45 UTC, jerryz123 requested changes

2024-04-12 22:45 UTC, jerryz123 commented on generators/chipyard/src/main/scala/config/fragments/SubsystemFragments.scala
> +class WithSV48IfPossible extends Config((site, here, up) => {
Nit, this should be in TileFragments, PgLevels only affects tiles.

2024-04-12 22:49 UTC, tymcauley commented
Just curious, what's the motivation behind this change? Working on designs with more than 512 GiB of virtual address space?

2024-04-12 23:22 UTC, abejgonzalez commented
> Just curious, what's the motivation behind this change? Working on designs with more than 512 GiB of virtual address space?

Some projects here in Berkeley are using open-source code that uses SV48 as a default (for example: https://github.com/google/tcmalloc/blob/5ed309d3de0c647a91bb41b2be68603c39aef452/tcmalloc/internal/config.h#L135). So this is just matching the default VA space to those applications (since I think it's fairly innocuous to add more space).

2024-04-15 18:24 UTC, jerryz123 approved these changes

2024-04-15 21:12 UTC, merged